### PR TITLE
Allow repeat views to be excluded

### PR DESCRIPTION
**Pull request by WillJW**
See: https://wordpress.org/support/topic/feature-request-ignoring-refresh-hits?replies=2#post-7303279

### CODE REVIEW

**Comment by masoud11** [comment]
please consider adding this option to the plugin.
this option is needed.
you can even make it better, with extending the option, rather just yes/no
maybe by put these options:
Allow repeat views to be excluded ?
1 - No
1 - Yes, with ip or cookie
2 - Yes, with both ip and cookie

thanks.

**Comment by zengxiaoluan** [comment]
我觉得这个功能很实用，不应该刷新页面就增加一次阅读量。

**Comment by zengxiaoluan** [comment]
test

**Comment by zengxiaoluan** [comment]
大幅度

**Pull request closed without merging**
